(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const d="https://api.thecatapi.com/v1",a="live_aIticapc5yMKLwBj7F4yaqx5l1ORt0AS6YUa15623BhG0txC4b6GwSarHvE9PX3u";function l(){return fetch(`${d}/breeds`,{headers:{"x-api-key":a}}).then(t=>{if(!t.ok)throw new Error(t.statusText||"Error");return t.json()})}function u(o){const t="/images/search",c=new URLSearchParams({api_key:a,breed_ids:o});return fetch(`${d}${t}?${c}`).then(s=>{if(!s.ok)throw new Error(s.statusText||"Error");return s.json()})}const n={selectBreed:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),error:document.querySelector(".error")};l().then(o=>{n.selectBreed.insertAdjacentHTML("beforeend",m(o)),n.selectBreed.classList.remove("hidden"),n.loader.classList.add("hidden")}).catch(o=>{n.loader.classList.add("hidden"),n.error.classList.remove("hidden")});n.selectBreed.addEventListener("change",f);console.dir(n.selectBreed);function f(o){o.currentTarget.value&&u(o.currentTarget.value).then(t=>{n.loader.classList.remove("hidden"),n.catInfo.classList.add("hidden"),setTimeout(()=>{n.catInfo.classList.remove("hidden"),n.catInfo.innerHTML=h(t[0]),n.loader.classList.add("hidden")},500)}).catch(t=>{n.selectBreed.classList.add("hidden"),n.error.classList.remove("hidden")})}function h(o){const{breeds:t,url:c}=o,{name:s,description:e,temperament:r}=t[0];return console.log(r),`
        <img src="${c}" alt="${s}" width="500">
        <div class="cat-description">
            <h2>${s}</h2>
            <p>${e}</p>
            <p><b>Temperament:</b> ${r}</p>
        </div>`}function m(o){return o.map(({id:t,name:c})=>`
        <option value="${t}">${c}</option>
        `).join("")}
//# sourceMappingURL=commonHelpers.js.map
